// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase App.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiz12U04fE1poTdMZxgeOeTo93IAtT0DE',
    appId: '1:699854133780:web:8d53baf01a5e35d3e0a501',
    messagingSenderId: '699854133780',
    projectId: 'resume-ai-analyzer-df8fc',
    authDomain: 'resume-ai-analyzer-df8fc.firebaseapp.com',
    storageBucket: 'resume-ai-analyzer-df8fc.firebasestorage.app',
    measurementId: 'G-V7P5XBD1Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLFM2EcjiyBR1qYjaKaD_UTKcXNH9iWfQ',
    appId: '1:699854133780:android:378fb751aaa825e0e0a501',
    messagingSenderId: '699854133780',
    projectId: 'resume-ai-analyzer-df8fc',
    storageBucket: 'resume-ai-analyzer-df8fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVUcAGmyMZI-Gz2VXO5r7fzl5sLG5MEE',
    appId: '1:699854133780:ios:e7521060234d6529e0a501',
    messagingSenderId: '699854133780',
    projectId: 'resume-ai-analyzer-df8fc',
    storageBucket: 'resume-ai-analyzer-df8fc.firebasestorage.app',
    iosBundleId: 'com.resumeai.resumeAiFlutter',
  );
}
