/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Core MD3 palette tokens
        "primary":                    "#0c1427",
        "on-primary":                 "#ffffff",
        "primary-container":          "#21283c",
        "on-primary-container":       "#888fa7",
        "primary-fixed":              "#dae2fd",
        "primary-fixed-dim":          "#bec6e0",
        "on-primary-fixed":           "#131b2e",
        "on-primary-fixed-variant":   "#3f465c",
        "secondary":                  "#505f76",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#d0e1fb",
        "on-secondary-container":     "#54647a",
        "secondary-fixed":            "#d3e4fe",
        "secondary-fixed-dim":        "#b7c8e1",
        "on-secondary-fixed":         "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary":                   "#00190e",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#00301e",
        "on-tertiary-container":      "#00a472",
        "tertiary-fixed":             "#6ffbbe",
        "tertiary-fixed-dim":         "#4edea3",
        "on-tertiary-fixed":          "#002113",
        "on-tertiary-fixed-variant":  "#005236",
        "surface":                    "#f7f9fb",
        "surface-dim":                "#d8dadc",
        "surface-bright":             "#f7f9fb",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f4f6",
        "surface-container":          "#eceef0",
        "surface-container-high":     "#e6e8ea",
        "surface-container-highest":  "#e0e3e5",
        "surface-variant":            "#e0e3e5",
        "on-surface":                 "#191c1e",
        "on-surface-variant":         "#45474c",
        "background":                 "#f7f9fb",
        "on-background":              "#191c1e",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
        "outline":                    "#75777d",
        "outline-variant":            "#c5c6cd",
        "inverse-surface":            "#2d3133",
        "inverse-on-surface":         "#eff1f3",
        "inverse-primary":            "#bec6e0",
        "surface-tint":               "#565e74",
        // Landing page accent (kept for legacy use in Landing.jsx)
        "accent":                     "#4edea3",
      },
      fontFamily: {
        heading:  ["'Space Grotesk'", "sans-serif"],
        headline: ["'Space Grotesk'", "sans-serif"],
        sans:     ["'Inter'", "sans-serif"],
        body:     ["'Inter'", "sans-serif"],
        label:    ["'Inter'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
}
