# Generated by Django 4.2.7 on 2025-10-22 19:53

from django.db import migrations, models
import django.db.models.deletion
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('must_have', models.JSONField(blank=True, default=list)),
                ('nice_to_have', models.JSONField(blank=True, default=list)),
                ('min_exp', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('shortlist_threshold', models.IntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=resumes.models.resume_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('insights', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('match_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('readability_score', models.IntegerField(default=0)),
                ('structure_score', models.IntegerField(default=0)),
                ('present_keywords', models.TextField(blank=True)),
                ('missing_keywords', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='resumes.requisition')),
            ],
            options={
                'ordering': ['-match_score', '-total_score', '-created_at'],
            },
        ),
    ]
