# Generated by Django 5.2.9 on 2026-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_requisition_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('rejected', 'Not selected'), ('hired', 'Hired')], default='new', max_length=20),
        ),
    ]
