# Generated by Django 5.2.7 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_analysisrecord_firebaseuser_analysisembedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsession",
            name="job_profile",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisrecord",
            name="job_profile",
            field=models.JSONField(blank=True, null=True),
        ),
    ]

