# Generated by Django 5.2.7 on 2026-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_analysisrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
