# Generated by Antigravity on 2026-04-18
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_analysisrecord_text_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
