# Generated by Django 4.2.25 on 2026-04-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_firebaseuser_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='is_heuristic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
