# Generated by Django 4.2.25 on 2026-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_analysisrecord_is_heuristic_firebaseuser_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='role_onboarding_done',
            field=models.BooleanField(default=False),
        ),
    ]
