# Generated by Django 4.2.25 on 2026-05-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_firebaseuser_role_onboarding_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
