# Generated by Django 4.2.25 on 2026-05-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_analysisrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrecord',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='recruiter_resumes/%Y/%m/%d/'),
        ),
    ]
